#!/bin/sh

# NOTA: Este archivo es un script. Asegúrate de hacerlo ejecutable (chmod +x).
# Se ejecuta desde Sway para gestionar el apagado de pantalla y bloqueo.

exec swayidle -w \
    \
    timeout 900 'swaylock -f' \
    \
    timeout 1200 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
    \
    timeout 1800 'systemctl suspend' \
    \
    before-sleep 'swaylock -f'
