#!/bin/sh
# Script para manejar apagado de pantalla y bloqueo en Sway

# Asegúrate de hacerlo ejecutable:
# chmod +x ~/.config/sway/swayidle.sh

swayidle -w \
    timeout 900 'swaylock -f' \
    timeout 1200 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    timeout 1800 'systemctl suspend' \
    before-sleep 'swaylock -f'

